version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://34.71.69.213:3306/Restaurante_Mexicano
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: restaurante-mexicano
